CLASS zcl_jrz_c367_c2_06 DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC
  GLOBAL FRIENDS zcl_jrz_c367_c2_07.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
    DATA: capital TYPE string.
ENDCLASS.



CLASS zcl_jrz_c367_c2_06 IMPLEMENTATION.
ENDCLASS.
